const restaurants = {
  dusale: {
    id: 1,
    label: "",
    description: "",
    location: "",
    phonenumber: "",
    pic1: "",
    pic2: "",
    pic3: "",
  },
  dusale: {
    id: 2,
    label: "",
    description: "",
    location: "",
    phonenumber: "",
    pic1: "",
    pic2: "",
    pic3: "",
  },
  summerbody: {
    id: 3,
    label: "",
    description: "",
    location: "",
    phonenumber: "",
    pic1: "",
    pic2: "",
    pic3: "",
  },
  summerbody: {
    id: 4,
    label: "",
    description: "",
    location: "",
    phonenumber: "",
    pic1: "",
    pic2: "",
    pic3: "",
  },
  pasletemps: {
    id: 5,
    label: "",
    description: "",
    location: "",
    phonenumber: "",
    pic1: "",
    pic2: "",
    pic3: "",
  },
  pasletemps: {
    id: 6,
    label: "",
    description: "",
    location: "",
    phonenumber: "",
    pic1: "",
    pic2: "",
    pic3: "",
  },
  mangerliquide: {
    id: 7,
    label: "",
    description: "",
    location: "",
    phonenumber: "",
    pic1: "",
    pic2: "",
    pic3: "",
  },
  mangerliquide: {
    id: 8,
    label: "",
    description: "",
    location: "",
    phonenumber: "",
    pic1: "",
    pic2: "",
    pic3: "",
  },
};
